### ISSUE TITLE
Panic on shutdown

### ISSUE THREAD

**Issue by porjo** [mailgun/vulcand#206]
I run Vulcand in a docker container, controlled by systemd. I've noticed it panics sometimes when Systemd shuts it down. The following is an example log showing an unclean shutdown:

```
Apr 24 05:55:31 bris01 systemd[1]: Stopping Vulcan Reverse Proxy...
Apr 24 05:55:39 bris01 docker[20831]: panic: runtime error: send on closed channel
Apr 24 05:55:39 bris01 docker[20831]: goroutine 37068 [running]:
Apr 24 05:55:39 bris01 docker[20831]: runtime.panic(0x85f860, 0xb4d6be)
Apr 24 05:55:39 bris01 docker[20831]: /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
Apr 24 05:55:39 bris01 docker[20831]: github.com/mailgun/vulcand/supervisor.func·002()
Apr 24 05:55:39 bris01 docker[20831]: /home/foo/go/src/github.com/mailgun/vulcand/supervisor/supervisor.go:200 +0x1f8
Apr 24 05:55:39 bris01 docker[20831]: created by github.com/mailgun/vulcand/supervisor.(*Supervisor).init
Apr 24 05:55:39 bris01 docker[20831]: /home/foo/go/src/github.com/mailgun/vulcand/supervisor/supervisor.go:207 +0x730
Apr 24 05:55:39 bris01 docker[20831]: goroutine 16 [chan receive]:
Apr 24 05:55:39 bris01 docker[20831]: github.com/mailgun/vulcand/supervisor.(*Supervisor).Stop(0xc2080600a0, 0x1)
Apr 24 05:55:39 bris01 docker[20831]: /home/foo/go/src/github.com/mailgun/vulcand/supervisor/supervisor.go:291 +0x7d
Apr 24 05:55:39 bris01 docker[20831]: github.com/mailgun/vulcand/service.(*Service).Start(0xc208080160, 0x0, 0x0)
Apr 24 05:55:39 bris01 docker[20831]: /home/foo/go/src/github.com/mailgun/vulcand/service/service.go:126 +0xa5b
Apr 24 05:55:39 bris01 docker[20831]: github.com/mailgun/vulcand/service.Run(0xc20804c520, 0x0, 0x0)
Apr 24 05:55:39 bris01 docker[20831]: /home/foo/go/src/github.com/mailgun/vulcand/service/service.go:36 +0x223
Apr 24 05:55:39 bris01 docker[20831]: main.main()
[...snip...]
Apr 24 05:55:40 bris01 systemd[1]: vulcand.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 24 05:55:40 bris01 systemd[1]: Stopped vulcand.service.
Apr 24 05:55:40 bris01 systemd[1]: Unit vulcand.service entered failed state.
Apr 24 05:55:40 bris01 systemd[1]: vulcand.service failed.
```

**Comment by klizhentas** [comment]
Interesting, will try to debug this case
